name: magmap
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy
  - drms
  - h5py >= 3.0.0
  - matplotlib
  - numpy
  - pandas < 2.0.0
  - python
  - pytz
  - scipy
  - six
  - sunpy >= 3.1.8
  - opencv

