name: magmap
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy
  - drms
  - h5py
  - matplotlib
  - mysqlclient
  - numpy
  - python
  - scipy
  - sqlalchemy-utils
  - sunpy >= 3.1.8
  - opencv
  - notebook
  - mkdocs-material
  - mkdocs-jupyter
